---
- name: Create random password
  ansible.builtin.set_fact:
    random_password: "{{ '' | generate_password }}"
  register: result

- name: Add new user
  ibm.ibm_zos_core.zos_tso_command:
    commands: "{{ lookup('template', '../templates/add-user.j2') }}"

- name: Permit access to resources
  ibm.ibm_zos_core.zos_tso_command:
    commands: "{{ lookup('template', '../templates/update-resource-access.j2') }}"
  with_items: "{{ resources_to_permit }}"
  when: resources_to_permit is defined and resources_to_permit and resources_to_permit | length > 0

- name: Add to groups
  ibm.ibm_zos_core.zos_tso_command:
    commands: "{{ lookup('template', '../templates/connect-user-to-group.j2') }}"
  with_items: "{{ groups_to_connect }}"
  when: groups_to_connect is defined and groups_to_connect and groups_to_connect | length > 0
