---
- name: Configure pgadmin container
  hosts: webservers
  become: true

  vars:
    pgadmin_service_name: app-pgadmin

    pgadmin_container:
      name: pgadmin
      restart: false
      image: docker.io/dpage/pgadmin4:7.5
      state: started
      env:
        PGADMIN_DEFAULT_EMAIL: student@example.com
        PGADMIN_DEFAULT_PASSWORD: learn_ansible
      generate_systemd:
        path: /etc/systemd/system/
        container_prefix: app
        restart_policy: always
      ports:
        - 8083:80
      network: bridge

  tasks:
    # - name: Run podman container using pgadmin_container var

    # - name: Start, enable and reload daemon for {{ pgadmin_service_name }}
