---

- name: MySQL stuff with lightspeed

  vars:
    db_name: MyDatabase

  tasks:
  
    - name: Install MySQL
      ansible.builtin.package:
        name: mysql-server
        state: present
    
    - name: Start the MySQL service
      ansible.builtin.service:
        name: mysql
        state: started
    
    - name: Create the application database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
    
    - name: Install OpenShift oc CLI
      ansible.builtin.package:
        name: oc
        state: present
    
    - name: Enable sudo for the group wheel
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: ^%wheel
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
    
      
    - name: Get a virtual machine state from VSphere using the module community.vmware
      community.vmware.vmware_guest_info:
        hostname: "{{ _hostname_ }}"
        username: "{{ _username_ }}"
        password: "{{ _password_ }}"
        datacenter: "{{ _datacenter_ }}"
        folder: "{{ _folder_ }}"
        name: "{{ _name_ }}"
      register: vm_info
    



    



